######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 2 15:42:02 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += common.h glo.h window.h
SOURCES += glo.cpp main.cpp window.cpp
